language: node_js
matrix:
  include:
    - node_js: "8"
    - node_js: "10"
    - node_js: "12"
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - export CHROME_PATH="$(pwd)/chrome-linux/chrome"
  - yarn build
script:
  - yarn test-formatting
  - yarn type-check
  - yarn test
addons:
  chrome: stable
services:
  - xvfb
