blank_issues_enabled: true
contact_links:
  - name: BrowserBox Community Support
    url: https://github.com/BrowserBox/BrowserBox/discussions
    about: Please ask and answer questions here.
  - name: BrowserBox security.txt
    url: https://dosyago.com/security.txt
    about: Please report security vulnerabilities here.

