#!/usr/bin/env bash

if [[ -z "$1" ]]; then
  echo "no domain in first position. failing"
  exit 1
fi

if [[ -z "$2" ]]; then
  echo "no destination directory in second position. failing"
  exit 1
fi

mkdir -p $2
. /etc/os-release
if [[ $ID == *"bsd" ]] || [[ -d /usr/local/etc/letsencrypt/live/$1 ]]; then
  cp -r -L /usr/local/etc/letsencrypt/live/$1/* $2
else
  cp -r -L /etc/letsencrypt/live/$1/* $2
fi
