name: Debug Workflow with SSH on Matrix

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  debug:
    # Define the matrix of operating systems
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up tmate for SSH debugging
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        # Optional: Set a timeout for the session (e.g., 15 minutes)
        timeout-minutes: 50

      # Add your custom steps here (this is a blank template)
      # Example:
      # - name: Run a command
      #   run: echo "Hello from ${{ matrix.os }}"
