name: Update version.json and package.json on Tag Creation

on:
  create:
    ref_type: tag
    ref: v*

jobs:
  update-version-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Only run if the ref is a tag and matches v*
    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')

    steps:
      - name: Debug Event Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.event.ref }}"
          echo "Ref Type: ${{ github.event.ref_type }}"
          echo "Full Ref: ${{ github.ref }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.ref }}

      - name: Set up SSH for signing
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          ssh-keygen -y -P "" -f ~/ssh_key > ~/.ssh/bbx_signing_key.pub
          git config --global user.signingkey ~/.ssh/bbx_signing_key.pub
          git config --global gpg.format ssh
          git config --global gpg.ssh.program ssh-keygen
          git config --global commit.gpgsign true
          echo "SSH_AUTH_SOCK=/tmp/ssh-agent.sock" >> $GITHUB_ENV
          ssh-agent -a /tmp/ssh-agent.sock > /tmp/ssh-agent.env
          source /tmp/ssh-agent.env
          ssh-add ~/ssh_key

      - name: Configure Git
        run: |
          git config --global user.name "DOSAYGO Engineering"
          git config --global user.email "development.team@dosaygo.com"

      - name: Debug file state
        run: |
          echo "Repository contents:"
          ls -la
          if [ -f package.json ]; then
            echo "Current package.json:"
            cat package.json
          else
            echo "package.json not found"
            exit 1
          fi

      - name: Update version.json and package.json
        run: |
          TAG_NAME=${{ github.event.ref }}
          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag '$TAG_NAME' does not match expected format (e.g., v10.5.1)"
            exit 1
          fi
          echo "{\"tag\": \"$TAG_NAME\"}" > version.json
          # Remove 'v' prefix for package.json version (e.g., v10.5.1 -> 10.5.1)
          VERSION=${TAG_NAME#v}
          jq ".version = \"$VERSION\"" package.json > package.json.tmp && mv package.json.tmp package.json
          echo "Updated version.json:"
          cat version.json
          echo "Updated package.json:"
          cat package.json

      - name: Create branch and commit
        run: |
          TAG_NAME=${{ github.event.ref }}
          BRANCH_NAME="update-version-json-$TAG_NAME"
          git checkout -b "$BRANCH_NAME"
          git add --force version.json package.json
          echo "Git status:"
          git status
          echo "Git diff:"
          git diff --cached
          git commit -m "Update version.json and package.json for $TAG_NAME"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-version-json-${{ github.event.ref }}
          base: main
          title: Update version.json and package.json for ${{ github.event.ref }}
          body: |
            This PR updates `version.json` and `package.json` with the tag `${{ github.event.ref }}` for the latest release.
            Please review and merge to include it in the main branch.
          reviewers: o0101
          commit-message: Update version.json and package.json for ${{ github.event.ref }}
          committer-name: DOSAYGO Engineering
          committer-email: development.team@dosaygo.com
          delete-branch: true

      - name: Clean up SSH
        if: always()
        run: |
          rm -f ~/ssh_key
          rm -rf ~/.ssh
